import java.util.List;

/** Banco de perguntas do quiz: 5 etapas com 4 perguntas cada, uma única resposta correta em cada. */
final class QuestionBank {

    private QuestionBank() {
    }

    static final List<String> PARTS = List.of(
            "Senhas e autenticação",
            "Phishing e engenharia social",
            "Redes e navegação segura",
            "Dispositivos, malware e backup",
            "Privacidade e boas práticas");

    static final List<Question> ALL = List.of(
            new Question(0, "Qual destas senhas é a mais segura?",
                    List.of("Kaua2005!",
                            "cavalo-bateria-grampo-lunar-47",
                            "12345678",
                            "senha@123"),
                    1,
                    "Senhas longas e imprevisíveis (frases com várias palavras aleatórias) são muito mais difíceis de adivinhar do que senhas curtas com data de nascimento ou padrões comuns."),
            new Question(0, "O que é a autenticação em dois fatores (2FA)?",
                    List.of("Usar duas senhas idênticas em contas diferentes",
                            "Trocar a senha duas vezes por ano",
                            "Exigir, além da senha, uma segunda prova de identidade",
                            "Entrar na mesma conta em dois aparelhos"),
                    2,
                    "O 2FA soma à senha (algo que você sabe) outro fator, como um código no app ou uma chave física (algo que você tem). Mesmo com a senha vazada, o invasor não entra sozinho."),
            new Question(0, "Qual é a melhor prática para lidar com dezenas de contas online?",
                    List.of("Anotar tudo em um arquivo senhas.txt na área de trabalho",
                            "Usar a mesma senha forte em todas",
                            "Usar variações da mesma senha (senha1, senha2...)",
                            "Usar um gerenciador de senhas, com uma senha única e forte por conta"),
                    3,
                    "Senhas repetidas ou parecidas permitem que um único vazamento comprometa várias contas. O gerenciador gera e guarda senhas únicas, exigindo que você lembre só de uma senha mestra."),
            new Question(0, "Qual forma de 2FA costuma ser a mais resistente a ataques?",
                    List.of("App autenticador ou chave de segurança física",
                            "Código por SMS",
                            "Perguntas de segurança (nome da mãe, pet...)",
                            "Código enviado para um e-mail sem proteção extra"),
                    0,
                    "SMS pode ser interceptado por golpes de troca de chip (SIM swap). Apps autenticadores e chaves físicas são mais difíceis de burlar."),
            new Question(1, "Qual é um sinal típico de mensagem de phishing?",
                    List.of("Mensagem com seu nome completo e sem nenhum link",
                            "E-mail do domínio oficial que não pede nada",
                            "Urgência, ameaça de bloqueio e link suspeito pedindo seus dados",
                            "Aviso de atualização exibido pelo próprio sistema operacional"),
                    2,
                    "Golpistas criam pressão (\"sua conta será bloqueada hoje\") para que você aja sem pensar. Links estranhos e pedidos de dados pessoais reforçam o alerta."),
            new Question(1, "Você recebe um SMS do \"banco\" com um link para \"regularizar a conta\". O que fazer?",
                    List.of("Clicar rápido para evitar o bloqueio",
                            "Ignorar o link e entrar pelo app oficial ou ligar ao número impresso no cartão",
                            "Responder o SMS perguntando se é verdadeiro",
                            "Encaminhar aos amigos para avisá-los, com o link"),
                    1,
                    "Nunca use os canais fornecidos na mensagem suspeita. Confirme sempre por um canal que você mesmo conhece e sabe ser oficial."),
            new Question(1, "O que é spear phishing?",
                    List.of("Ataque de força bruta contra senhas",
                            "Vírus que se espalha por pendrive",
                            "Envio em massa de e-mails genéricos",
                            "Golpe direcionado a uma pessoa ou empresa específica, com informações personalizadas"),
                    3,
                    "No spear phishing o atacante pesquisa a vítima (cargo, colegas, fornecedores) para criar uma mensagem muito convincente, o que o torna mais perigoso que o phishing genérico."),
            new Question(1, "Alguém liga dizendo ser do \"suporte técnico\" e pede o código de verificação que você acabou de receber por SMS. Isso é:",
                    List.of("Engenharia social: códigos de verificação jamais devem ser compartilhados",
                            "Procedimento normal de suporte",
                            "Aceitável se a pessoa souber o seu nome",
                            "Seguro se a ligação vier de um número com DDD local"),
                    0,
                    "Empresas legítimas não pedem códigos de verificação. Esse código é justamente o que o golpista precisa para concluir o acesso à sua conta."),
            new Question(2, "O cadeado (HTTPS) ao lado do endereço de um site indica que:",
                    List.of("O site é confiável e legítimo",
                            "A conexão com o site é criptografada, mas isso não garante que o site seja honesto",
                            "O site está livre de vírus",
                            "O site não coleta dados pessoais"),
                    1,
                    "HTTPS protege os dados em trânsito. Sites de golpe também podem ter cadeado, então confira sempre o endereço exato."),
            new Question(2, "Você está no Wi-Fi aberto de um aeroporto e precisa acessar o banco. O mais prudente é:",
                    List.of("Acessar normalmente, pois o cadeado garante tudo",
                            "Desativar o firewall para conectar mais rápido",
                            "Pedir a senha do Wi-Fi a desconhecidos",
                            "Evitar operações sensíveis ou usar VPN/dados móveis"),
                    3,
                    "Redes públicas podem ser monitoradas ou falsificadas (\"evil twin\"). Para operações sensíveis, prefira dados móveis ou uma VPN confiável."),
            new Question(2, "O que uma VPN faz de fato?",
                    List.of("Remove vírus do aparelho",
                            "Acelera sempre a conexão de internet",
                            "Criptografa o tráfego até o servidor da VPN e oculta seu IP de quem está na rede local ou no site",
                            "Torna impossível ser rastreado na internet"),
                    2,
                    "A VPN protege o trânsito dos dados e mascara o IP, mas não elimina malwares, não impede phishing e não garante anonimato total."),
            new Question(2, "Qual é a forma mais segura de acessar o site do seu banco?",
                    List.of("Digitar o endereço oficial ou usar o app oficial do banco",
                            "Clicar no primeiro anúncio patrocinado do buscador",
                            "Abrir o link recebido por WhatsApp",
                            "Usar qualquer link que pareça familiar"),
                    0,
                    "Anúncios e links recebidos podem levar a cópias fraudulentas. O endereço digitado por você ou o app oficial evitam esse risco."),
            new Question(3, "Por que manter o sistema e os aplicativos atualizados é importante?",
                    List.of("As atualizações só mudam o visual",
                            "Elas corrigem vulnerabilidades que atacantes podem explorar",
                            "Elas deixam o aparelho mais lento de propósito",
                            "Servem apenas para renovar a licença"),
                    1,
                    "Muitos ataques exploram falhas já conhecidas e corrigidas. Quem não atualiza continua vulnerável a elas."),
            new Question(3, "O que é um ransomware?",
                    List.of("Programa que apenas exibe propagandas",
                            "Técnica para descobrir senhas por tentativa e erro",
                            "Malware que criptografa seus arquivos e exige pagamento para liberá-los",
                            "Golpe aplicado por ligação telefônica"),
                    2,
                    "O ransomware \"sequestra\" seus dados. A melhor defesa é manter backups atualizados e desconectados, além de evitar anexos e links suspeitos."),
            new Question(3, "O que significa a regra de backup 3-2-1?",
                    List.of("3 senhas, 2 fatores de autenticação e 1 antivírus",
                            "3 cópias dos arquivos guardadas no mesmo HD",
                            "3 backups por ano, em 2 pastas e com 1 senha",
                            "3 cópias dos dados, em 2 tipos de mídia diferentes, com 1 cópia fora do local principal"),
                    3,
                    "Essa distribuição reduz o risco de perder tudo por falha de hardware, roubo, incêndio ou ransomware."),
            new Question(3, "Qual atitude é mais segura ao instalar um aplicativo?",
                    List.of("Baixar de qualquer site, desde que seja gratuito",
                            "Instalar pela loja oficial e revisar as permissões que o app pede",
                            "Instalar versões \"crackeadas\" para economizar",
                            "Aceitar todas as permissões sem ler"),
                    1,
                    "Lojas oficiais filtram boa parte dos apps maliciosos. Desconfie de apps que pedem permissões sem relação com sua função (como lanterna pedindo acesso aos contatos)."),
            new Question(4, "No Brasil, qual lei trata especificamente da proteção de dados pessoais?",
                    List.of("Lei de Direitos Autorais",
                            "Lei Seca",
                            "Lei Geral de Proteção de Dados (LGPD, Lei nº 13.709/2018)",
                            "Lei de Licitações"),
                    2,
                    "A LGPD define como empresas e órgãos podem coletar, usar, armazenar e compartilhar dados pessoais, e garante direitos aos titulares."),
            new Question(4, "O que diz o princípio do menor privilégio?",
                    List.of("Todos devem ser administradores para agilizar o trabalho",
                            "Uma conta de administrador deve ser compartilhada pela equipe",
                            "Nenhum usuário deve ter qualquer permissão",
                            "Cada pessoa deve ter apenas os acessos necessários à sua função"),
                    3,
                    "Quanto menos acessos, menor o estrago se uma conta for invadida ou usada por engano."),
            new Question(4, "Você perdeu o celular. Qual é a melhor primeira reação?",
                    List.of("Esperar alguns dias para ver se ele aparece",
                            "Bloquear ou apagar o aparelho remotamente, trocar senhas principais e avisar a operadora",
                            "Comprar outro e deixar o antigo para lá",
                            "Postar nas redes sociais pedindo ajuda"),
                    1,
                    "Agir rápido limita o acesso a contas, apps bancários e mensagens. Bloquear o chip também evita golpes usando o seu número."),
            new Question(4, "Por que os sites devem armazenar senhas como hash (com salt), e não em texto puro?",
                    List.of("Para economizar espaço no banco de dados",
                            "Para poder enviar a senha original por e-mail ao usuário",
                            "Para que um vazamento do banco não exponha diretamente as senhas",
                            "Para tornar o login mais rápido"),
                    2,
                    "O hash é uma transformação de mão única, e o salt dificulta ataques com tabelas prontas. Se o banco vazar, as senhas não ficam legíveis."));
}
